# Generated by Django 5.2.11 on 2026-02-28 03:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dr_first_name', models.CharField(max_length=50)),
                ('dr_last_name', models.CharField(max_length=50)),
                ('license_number', models.CharField(max_length=50, unique=True)),
                ('base_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('commission_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('joining_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vin', models.CharField(max_length=17, unique=True)),
                ('plate_number', models.CharField(max_length=15, unique=True)),
                ('model_year', models.IntegerField()),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('ON TRIP', 'On Trip'), ('MAINTENANCE', 'Maintenance')], default='AVAILABLE', max_length=20)),
                ('current_mileage', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='SalaryPayroll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_year', models.DateField()),
                ('trips_completed', models.IntegerField()),
                ('total_commissions', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fixed_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('net_payable', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid')], default='PENDING', max_length=10)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flapis.driver')),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('origin', models.CharField(max_length=255)),
                ('destination', models.CharField(max_length=255)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('revenue', models.DecimalField(decimal_places=2, max_digits=12)),
                ('fuel_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('toll_fees', models.DecimalField(decimal_places=2, max_digits=10)),
                ('other_expenses', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('PLANNED', 'Planned'), ('ONGOING', 'Ongoing'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='PLANNED', max_length=20)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flapis.driver')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flapis.vehicle')),
            ],
        ),
    ]
